### ISSUE TITLE
[Web] Default date ranges for all filter date pickers 

### ISSUE THREAD

**Issue by cquinn5** [ssxsora/VMA-Web-App#16]
We currently have it for satisfaction filters, but not for post-proc, we should have a better idea of what this range should be for post-proc after user testing today

**Comment by cquinn5** [comment]
Oh no you're right I am wrong. Should we make it so it takes 2 weeks of valid data if nothing is found within the last 2 weeks?

**Comment by ssxsora** [comment]
Yeah, as the default. But we can update it tonight when we know forealsies

**Comment by ssxsora** [comment]
The default dates will make postproc and patsat reports show 2 weeks' worth of data
