### ISSUE TITLE
[Web] Automatic BMI calculation based upon height and weight inputted

### ISSUE THREAD

**Issue by sweng270** [ssxsora/VMA-Web-App#19]
[Web Application - Pre-Procedure Questionnaire]

- The BMI needs to be automatically generated based upon the weight (lbs) and height (inches) inputted into the pre-procedure questionnaire form.
- The formula for calculating BMI is shown in the image attached to this issue/ticket. (**NOTE:** there are two formulas for calculating a patient's BMI; one based upon weight in kilograms and height in meters and another one with weight in pounds and height in inches.

![bmi_formula](https://user-images.githubusercontent.com/16547218/38645340-ba8492c8-3db1-11e8-826b-600be787f950.png)

**Comment by cquinn5** [comment]
this will probably need to be done by javascript in templates/fillPreProc.html

**Comment by ssxsora** [comment]
yep that's what i'm planning to do tonight
