### ISSUE TITLE
attribute management (django admin)

### ISSUE THREAD

**Issue by cquinn5** [ssxsora/VMA-Web-App#24]

**Comment by mkcrto** [comment]
@cquinn5  what does this bug refer to?

**Comment by mkcrto** [comment]
Need to create an admin interface so attributes (like isBloodThinner, etc) can be created/updated/deleted. The dropdown on the questionnaire management page will then be made to pull from those values (separate issue).

**Comment by mkcrto** [comment]
Created an admin interface to allow for creating, updating, and deleting instruction attributes.
