### ISSUE TITLE
Adding cross origin resource sharing

### ISSUE THREAD

**Issue by ssxsora** [ssxsora/VMA-Web-App#29]
Need to add a plugin & some changes to allow the mobile apps to access the web server (not localhost, but our actual server)

http://www.django-rest-framework.org/topics/ajax-csrf-cors/
https://github.com/ottoyiu/django-cors-headers/

**Comment by mkcrto** [comment]
I have rebuilt the cloud instance with the current versions of the web app and the db. I just need to run the additional commands referenced in the links above and update the setup doc appropriately.

**Comment by mkcrto** [comment]
I’ve installed the django-cors-headers package and modified the Django settings file to add the app and use the middleware. Currently, when trying to access the API via Postman and Insomnia, I just keep getting the sign in page. Need to investigate further.

**Comment by mkcrto** [comment]
Added the required configuration for CORS to the production web server and updated the setup documentation.
