### ISSUE TITLE
dbinterfaces/appointmentInterface: getAppointmentsByMedProcID function defined twice

### ISSUE THREAD

**Issue by D-Krest** [ssxsora/VMA-Web-App#32]
There are two definitions for `getAppointmentsByMedProcID`:
`def getAppointmentsByMedProcID(med_proc_id)`
`def getAppointmentsByMedProcID(doctor_id)`

The latter should be renamed `getAppointmentsByDoctorID` and fixed wherever it is called upon.

**Comment by cquinn5** [comment]
I believe this has no impact, so I changed it. please advise if any issues arise

**Comment by ssxsora** [comment]
We should delete the doctor_id one is we haven't yet

**Comment by cquinn5** [comment]
Why delete it? I just changed it to `getAppointmentsByDoctorID(doctor_id)`

**Comment by ssxsora** [comment]
Ooh ok. Nvm then. Feel free to close it since it's complete
