### ISSUE TITLE
dbinterfaces/appointmentInterface: changeAppointmentAppointmentDate not setting dates to the correct timezone

### ISSUE THREAD

**Issue by D-Krest** [ssxsora/VMA-Web-App#34]
The following test case fails to change the appointment date to the correct timezone:

```
@pytest.mark.django_db
def testChangeAppointmentAppointmentDate():
	appointment = appointmentInterface.getAppointment(5)

	assert appointment is not None
	assert appointment.appointmentid == 5
	assert str(appointment.appointmentdate) == '2017-04-30 20:45:00+00:00'

	appointmentInterface.changeAppointmentAppointmentDate(5,'2018-05-20T14:30')
	appointment = appointmentInterface.getAppointment(5)

	assert appointment is not None
	assert appointment.appointmentid == 5
	assert str(appointment.appointmentdate) == '2018-05-20 14:30:00+00:00' # assertion failure
```
The failed assertion labeled above those the following error:
`AssertionError: assert '2018-05-20 19:30:00+00:00' == '2018-05-20 14:30:00+00:00'`

All dates stored in the database are returned as UTC `datetime` objects to VMAWeb. However it seems that inputted dates for changes or addition to date attributes are seen within their set timezone and are offset to UTC upon insertion/modification to the database.

This will likely affect most every function beyond the appointmentInterface that makes use of date attributes.

**Comment by cquinn5** [comment]
https://github.com/ssxsora/VMA-DB/issues/2

These two may be related, I might have done a bad by filing that under DB bugs

**Comment by cquinn5** [comment]
I turned Time Zone support in Django settings OFF, and I stopped seeing some errors. 

I am going to keep this ticket open while we determine scope (which may be large)

**Comment by cquinn5** [comment]
I'm going to close this ticket now, I think we've solved this by using the server time (django default if time zones aren't turned on) and using the ISO standard wherever possible
