### ISSUE TITLE
dbinterfaces/appointmentInterface: Error occurs when deleting Appointments

### ISSUE THREAD

**Issue by D-Krest** [ssxsora/VMA-Web-App#35]
Both of the delete functions in the appointmentInterface (`deleteAppointment` and `deleteAllAppointmentsByMedicalProcedure`) throw an IntegrityError when attempted to be deleted. This means the given appointment is being used somewhere else as Foreign Key and is not deleting the associated child row before deleting itself. The IntegrityError seems to occur from an appointment being used as Foreign Key in the **instructionsperpatient** table (as the following error message illustrates):

IntegrityError(1451, 'Cannot delete or update a parent row: a foreign key constraint fails (`vma`.`instructionsperpatient`, CONSTRAINT `instructionsperpatient_fk_1` FOREIGN KEY (`appointmentID`) REFERENCES `appointment` (`appointmentID`))')

**Comment by cquinn5** [comment]
added the following block to appointmentInterface.deleteAppointment:

`	instructions = InstructionsPerPatient.objects.filter(appointmentid=int(appointment_id))

	for ins in instructions:
		instructionsPerPatientInterface.deleteInstructionsPerPatient(ins.instructionsperpatientid)`

almost exactly copies the survey response deletion, should work in a similar way.
