### ISSUE TITLE
dbinterfaces/doctorInterface: getDoctorIdByName throws FieldError when used

### ISSUE THREAD

**Issue by D-Krest** [ssxsora/VMA-Web-App#36]
The following test case results in a FieldError when using the `getDoctorIdByName` function from the doctorInterface:

```
@pytest.mark.django_db
def testGetDoctorIdByName():
	doctor_id = doctorInterface.getDoctorIdByName('Ira Kelberman')

	assert doctor_id == 1
```

The reason this occurs, through inspection of the source code, is in line 15:

`return Doctor.objects.get(name=str(doctor_name)).doctorid`

There is no `name` field in the database, there are `doctorFirstName` and `doctorLastName` fields however. This function needs to be fixed to have two arguments (for the first and last name) as well as being fixed wherever it is called upon elsewhere.

**Comment by cquinn5** [comment]
changed this to work as expected, and added a getDoctorIdByFirstLast where you can give both first and last name or give whole name and python will attempt to split by a space character in the string

`def getDoctorIdByName(doctor_name):
    doctor_name= str(doctor_name).split(sep=' ', maxsplit=1)
    doctor_first_name= doctor_name[0]
    doctor_last_name=doctor_name[1]
    try:
        return Doctor.objects.get(doctorfirstname=doctor_first_name, doctorlastname=doctor_last_name).doctorid
    except Doctor.DoesNotExist:
        return None

def getDoctorIdByFirstLast(doctor_first_name, doctor_last_name):
    try:
        return Doctor.objects.get(doctorfirstname=str(doctor_first_name), doctorlastname=str(doctor_last_name)).doctorid
    except Doctor.DoesNotExist:
        return None`
