### ISSUE TITLE
dbinterfaces/doctorInterface: deleteDoctor does not delete Foreign Key uses of a doctor to be deleted

### ISSUE THREAD

**Issue by D-Krest** [ssxsora/VMA-Web-App#37]
The following test case fails and throws an IntegrityError:

```
@pytest.mark.django_db
def testDeleteDoctor():
	num_doctors_before_delete = len(Doctor.objects.all())

	doctorInterface.deleteDoctor(1)

	num_doctors_after_delete = len(Doctor.objects.all())

	assert (num_doctors_before_delete - 1) == num_doctors_after_delete
```

As most other delete functions in the dbinterfaces, this should delete all references to the given doctor that is to be deleted before attempting to delete itself.

**Comment by ssxsora** [comment]
We never lose the ability to determine any unique row for any table since
we are using surrogate keys as our primary key :)
