### ISSUE TITLE
dbinterfaces/instructionsPerPatientInterface: changeInstructionsPerPatientName function obselete

### ISSUE THREAD

**Issue by D-Krest** [ssxsora/VMA-Web-App#39]
It seems to me upon inspection of the `changeInstructionsPerPatientName` function in the instructionsPerPatientInterface file, that there are no `firstname` or `lastname` attributes with the current schema so the use of this function will result in an error. If this method is not relevant any longer, please delete it from the instructionsPerPatientInterface.

**Comment by cquinn5** [comment]
Honestly, I don't think this is used. I based InstructionsPerPatient off of Doctor Interface

**Comment by ssxsora** [comment]
We can just delete the fuction

**Comment by cquinn5** [comment]
function deleted
