### ISSUE TITLE
dbinterfaces/surveyResponseInterface: add parsing of date string to datetime objects in getPatSatIndSummary or check for datetime object being passed

### ISSUE THREAD

**Issue by D-Krest** [ssxsora/VMA-Web-App#40]
Within the `getPatSatIndSummary` function in the surveyResponseInterface, it would be good to do one of the following operations to ensure the correct argument type:

1. Parse a given date string into a `datetime` object if a date string is provided
2. Check for `datetime` object types for both the `beginDate` and `endDate` objects; return a `None` object if improper arguments are supplied

Either operation will make it clearer to understand what the supplied arguments need to be and also handle erroneous input to the said function.

**Comment by ssxsora** [comment]
Completed; it will display no results and come up with a message on the GUI side
