### ISSUE TITLE
dbintefaces/getPostProcReport: Invalid startDate and endDate date strings still yield results

### ISSUE THREAD

**Issue by D-Krest** [ssxsora/VMA-Web-App#41]
The following test cases are built to pass:

```
@pytest.mark.django_db
def testGetPostProcReport():
	pat_sat_report = surveyResponseInterface.getPostProcReport('2016-01-01','3000-01-01')

	assert pat_sat_report is not None
	assert len(pat_sat_report) == 5


@pytest.mark.django_db
def testGetPostProcReportInvalidBeginDate():
	pat_sat_report = surveyResponseInterface.getPostProcReport('not a date','3000-01-01')

	assert pat_sat_report is not None
	assert len(pat_sat_report) == 5


@pytest.mark.django_db
def testGetPostProcReportInvalidEndDate():
	pat_sat_report = surveyResponseInterface.getPostProcReport('2016-01-01','not a date')

	assert pat_sat_report is not None
	assert len(pat_sat_report) == 0
```

However, I feel there should be some kind of date validation for the inputted date strings to see if they are valid ones. When an invalid beginDate is supplied, it seems the query just returns a tuple of results from that before the valid endDate. When an invalid endDate is supplied, an empty tuple is returned. Is this the expected behavior? If not, please update this issue to a bug to be fixed.

**Comment by ssxsora** [comment]
Completed; it will display no results and come up with a message on the GUI side
