### ISSUE TITLE
on fillpreproc survey load, location and doctor question selections must refresh

### ISSUE THREAD

**Issue by cquinn5** [ssxsora/VMA-Web-App#45]
these get populated during creation, so the logic needs to be moved to be on display

This makes it so new locations/doctors aren't added to the preproc screen

**Comment by cquinn5** [comment]
I added all_locations and all_doctors to the `context` of fillPreProc view, but I'm not sure how to insert those values into the select boxes of those questions @D-Krest @ssxsora 

is it like the `else if (questionTextArr[questionTextArr.length-1] == 'Patient PIN')` except with Procedure Location and Physician? I got that far, but I have no idea how to update the selection options

**Comment by ssxsora** [comment]
Check out Dave's code in the editSurvey.html page. I think that gives you a good idea on how it's done
