### ISSUE TITLE
Add an "Edit Attribute" admin page

### ISSUE THREAD

**Issue by ssxsora** [ssxsora/VMA-Web-App#46]
We need a page that allows users to add more attribute types for table insattribute

**Comment by cquinn5** [comment]
This is free standing so it can probably be an admin page?

**Comment by ssxsora** [comment]
That's what I'm thinking as well. It should be an easy one to deal with :)

**Comment by ssxsora** [comment]
wait a minute... @mkcrto  already completed this. It just has some weird bug where it isn't rendering
