### ISSUE TITLE
[Web] Open the PDF in a new window

### ISSUE THREAD

**Issue by ssxsora** [ssxsora/VMA-Web-App#5]
Right now, the PDF opens in the same window, therefore the user cannot navigate the website using the UI only (that is, the user doesn't click the back button and only relies on the site UI). We'd like the PDF to open as a new window OR wrap the PDF to be displayed in the website, so the menu is still on the top of the page and the user can move around the site.

**Comment by cquinn5** [comment]
templates/fillPreProc.html
added `target="_blank"` to line 11 <form> tag, makes PDF open in a new window but doesn't destroy the previous screen's data (thru a splash or something? idk)

**Comment by ssxsora** [comment]
redirect fillpreproc to index after submission redirect(fillPreProc)

**Comment by D-Krest** [comment]
templates/includes/splashScreen.html
added `onclick="window.history.go(-1)"` to line 21 (submit button)

Now, clicking the submit button on the splash screen navigates the given window back a page in the given window's history (for fillPreProc, this will push it back to the fillPreProc portal page). This does not affect other pages that use the splash screen that specified redirects (ie. the edit instructions/survey pages)
