### ISSUE TITLE
[Web] Date/Time Picker doesn't work in IE11

### ISSUE THREAD

**Issue by cquinn5** [ssxsora/VMA-Web-App#6]
will attach screenshot in a moment

**Comment by cquinn5** [comment]
![date time picker](https://user-images.githubusercontent.com/13007332/38470191-1d714df4-3b2d-11e8-98fc-9de8950cbf0b.PNG)

**Comment by ssxsora** [comment]
Potential solution: change datepicker to use picaday? Picaday also uses moment.js to change the date to the format we need for the DB, so all our dates in the DB can be turned back to be the standard YYYY/MM/DD HH:MM:SS

**Comment by sweng270** [comment]
I will double check and ask the office staff which internet browser they use at the office; in the worst case if this doesn't get fixed, we can put it as something that anyone who picks it up in the future can work on and we can note it in the user documentation.

**Comment by mkcrto** [comment]
@sweng270 did you have a chance to check with the office staff about this one?

**Comment by ssxsora** [comment]
switched to use pikaday
